/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guias5;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author NATANAEL MORENO
 */
public class guia1 extends javax.swing.JFrame {

    /**
     * Creates new form guia1
     */
    
    DefaultListModel modelo2= new DefaultListModel();
double da;
private int tama=10;
    public guia1() {
        initComponents();
      this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        diametro = new javax.swing.JTextField();
        circunferencia = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        esfera = new javax.swing.JButton();
        esfera1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diagonal = new javax.swing.JTextField();
        cubo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        promedio = new javax.swing.JTextField();
        promedio1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regresar.setText("REGRESAR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        jPanel1.add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("CALCULAR LA CIRCUNFERENCIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        diametro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diametroKeyTyped(evt);
            }
        });
        jPanel1.add(diametro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 159, -1));

        circunferencia.setText("CALCULAR");
        circunferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circunferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(circunferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CALCULAR EL VOLUMEN \nDE LA ESFERA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 40));

        esfera.setText("CALCULAR");
        esfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esferaActionPerformed(evt);
            }
        });
        jPanel1.add(esfera, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        esfera1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                esfera1KeyTyped(evt);
            }
        });
        jPanel1.add(esfera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 169, -1));

        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("CALCULAR EL VOLUMEN DEL CUBO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        diagonal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diagonalKeyTyped(evt);
            }
        });
        jPanel1.add(diagonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 158, -1));

        cubo.setText("CALCULAR");
        cubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuboActionPerformed(evt);
            }
        });
        jPanel1.add(cubo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("INGRESE EL DIAMETRO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("INGRESE LA DIAGONAL");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("INGRESE EL RADIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 240, -1));

        jLabel7.setBackground(new java.awt.Color(255, 204, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("resultado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        limpiar.setText("LIMPIAR");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        jPanel1.add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        salir.setText("SALIR");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel1.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 80, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("CALCULAR PROMEDIO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 10));

        promedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                promedioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                promedioKeyTyped(evt);
            }
        });
        jPanel1.add(promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 160, -1));

        promedio1.setText("CALCULAR");
        promedio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedio1ActionPerformed(evt);
            }
        });
        jPanel1.add(promedio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Plain-design-pattern-dark-background-image-HD-resolution-latest-pack-800x600.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        menuprincipal ventana = new menuprincipal(); 
          ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
             dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void circunferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circunferenciaActionPerformed
          double pi=3.1416;
      double valor= Double.parseDouble(diametro.getText());
    resultado.setText(String.valueOf(pi*valor +" m"));
       
    }//GEN-LAST:event_circunferenciaActionPerformed

    private void cuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuboActionPerformed
          Double a= Math.sqrt(3);
      double v= Double.parseDouble(diagonal.getText());
      double i= v/a;
      resultado.setText(String.valueOf(i*i*i   +"  cm cubico"));
    }//GEN-LAST:event_cuboActionPerformed

    private void esferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esferaActionPerformed
        double pi=3.14;
     double a=1.33;
       double valor1 = Double.parseDouble(esfera1.getText());
        resultado.setText(String.valueOf(a*pi*valor1*valor1*valor1 +" cm cubicos"));
    }//GEN-LAST:event_esferaActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
       
        diagonal.setText("");
        diametro.setText("");
        esfera1.setText("");
        resultado.setText("");
        promedio.setText("");
       
         promedio.setEnabled(true);
       
         
    }//GEN-LAST:event_limpiarActionPerformed

    private void promedio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedio1ActionPerformed
    
        double sum=0;
        for (int i=0; i<10;i++){
        sum=(sum+vector[i]);
        }
        double total=sum/10.0;
        resultado.setText(String.valueOf(total));
        promedio.setEnabled(false);
     
    }//GEN-LAST:event_promedio1ActionPerformed

    private void promedioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_promedioKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER && promedio.getText().length()!=0){
      int dato=Integer.parseInt(promedio.getText());
        int a = Contador();
        vector[a]=dato;
        if(a==9){
       // jButton1.setVisible(false);
       
        promedio.setEnabled(false);
        }
        promedio.setText("");
        
        }
    }//GEN-LAST:event_promedioKeyPressed

    private void promedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_promedioKeyTyped
       char car=evt.getKeyChar();
        if((car<'0' || car>'9') && (car<'.' || car>'.'))evt.consume();
   
         if(promedio.getText().length()==12){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_promedioKeyTyped

    private void diametroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diametroKeyTyped
         char car=evt.getKeyChar();
        if((car<'0' || car>'9') && (car<'.' || car>'.'))evt.consume();
   
         if(diametro.getText().length()==12){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_diametroKeyTyped

    private void diagonalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diagonalKeyTyped
        char car=evt.getKeyChar();
        if((car<'0' || car>'9') && (car<'.' || car>'.'))evt.consume();
   
         if(diagonal.getText().length()==12){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_diagonalKeyTyped

    private void esfera1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_esfera1KeyTyped
      char car=evt.getKeyChar();
        if((car<'0' || car>'9') && (car<'.' || car>'.'))evt.consume();
   
         if(esfera1.getText().length()==10){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
         }
    }//GEN-LAST:event_esfera1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guia1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guia1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circunferencia;
    private javax.swing.JButton cubo;
    private javax.swing.JTextField diagonal;
    private javax.swing.JTextField diametro;
    private javax.swing.JButton esfera;
    private javax.swing.JTextField esfera1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField promedio;
    private javax.swing.JButton promedio1;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
int suma=1;
    double vector[]=new double[10];
public int Contador()
{
suma=suma+1;
        return suma;
}}
