/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guias5;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author NATANAEL MORENO
 */
public class GUIA3 extends javax.swing.JFrame {

    /**
     * Creates new form GUIA3
     */
    DefaultListModel modelo1= new DefaultListModel();
    private DefaultComboBoxModel marca = new DefaultComboBoxModel();
    
    public GUIA3() {
        initComponents();
        mostrar.setModel(modelo1);
        this.setLocationRelativeTo(null);
        marca.addElement("SELECCIONE");
        marca.addElement("NEXUS");
        marca.addElement("PIXIE");
        marca.addElement("HUAWEI");
        marca.addElement("SONY");
        marca.addElement("APPLE");
        marca.addElement("SAMSUNG");
         marca.addElement("ALCATEL");
        marca.addElement("LG");
        marca.addElement("OTRA");
        cmbmarca.setModel(marca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cpu = new javax.swing.JTextField();
        pantalla = new javax.swing.JTextField();
        ram = new javax.swing.JTextField();
        garantia = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JList<>();
        ejecutar = new javax.swing.JButton();
        cmbmarca = new javax.swing.JComboBox<>();
        principal = new javax.swing.JCheckBox();
        secundaria = new javax.swing.JCheckBox();
        flash = new javax.swing.JCheckBox();
        principal1 = new javax.swing.JTextField();
        secundaria1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PUNTAJES DE MOVILES");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("CPU Numero de nucleos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("TAMAÑO DE PANTALLA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("CANTIDAD DE RAM");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("PIEMPO DE GARANTIA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 201, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("PRECIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 247, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("MARCA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 292, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("CAMARAS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        cpu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cpuKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cpuKeyTyped(evt);
            }
        });
        jPanel1.add(cpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 77, 150, -1));

        pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallaActionPerformed(evt);
            }
        });
        pantalla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pantallaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pantallaKeyTyped(evt);
            }
        });
        jPanel1.add(pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, -1));

        ram.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ramKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ramKeyTyped(evt);
            }
        });
        jPanel1.add(ram, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 158, 150, -1));

        garantia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                garantiaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                garantiaKeyTyped(evt);
            }
        });
        jPanel1.add(garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 198, 150, -1));

        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                precioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioKeyTyped(evt);
            }
        });
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 244, 150, -1));

        jScrollPane1.setViewportView(mostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 310, 150));

        ejecutar.setText("ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });
        jPanel1.add(ejecutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 410, 90, -1));

        jPanel1.add(cmbmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 289, 150, -1));

        principal.setText("PRINCIPAL");
        jPanel1.add(principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, -1, -1));

        secundaria.setText("SECUNDARIA");
        jPanel1.add(secundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        flash.setText("FLASH");
        jPanel1.add(flash, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));
        jPanel1.add(principal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, -1));
        jPanel1.add(secundaria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 370, 80, -1));

        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jButton2.setText("SALIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Plain-design-pattern-dark-background-image-HD-resolution-latest-pack-800x600.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pantallaActionPerformed

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
           int  nombre =Integer.parseInt(cpu.getText());
           double  nombre1 =Double.parseDouble(pantalla.getText());
           double  nombre2 =Double.parseDouble(ram.getText());
           double nombre3 =Double.parseDouble(garantia.getText());    
           double  nombre4 =Double.parseDouble(precio.getText()); 
          String combo=(String) (cmbmarca.getSelectedItem());
          String che= (principal.getActionCommand());
          String che1= (secundaria.getActionCommand());
          String fla=flash.getActionCommand();
       if(nombre>=0){
       modelo1.addElement("cpu : "+nombre);
       modelo1.addElement("pantalla : "+nombre1);
       modelo1.addElement("ram : "+nombre2);
       modelo1.addElement("garantia : "+nombre3);
       modelo1.addElement("precio : "+nombre4);
      modelo1.addElement("combo"+combo);
      modelo1.addElement(che+principal1.getText());
      modelo1.addElement(che1+secundaria1.getText());
       }
    }//GEN-LAST:event_ejecutarActionPerformed

    private void cpuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpuKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            pantalla.requestFocus();
        }   
    }//GEN-LAST:event_cpuKeyPressed

    private void cpuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpuKeyTyped
    
      char car=evt.getKeyChar();
        if(car<'0' || car>'9') evt.consume();
        if(cpu.getText().length()==2){
           int num;
        num=Integer.parseInt(cpu.getText()); 
         if(num>=1 || num<12){   
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
         }
    }//GEN-LAST:event_cpuKeyTyped

    private void pantallaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pantallaKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            ram.requestFocus();
        }
    }//GEN-LAST:event_pantallaKeyPressed

    private void pantallaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pantallaKeyTyped
         char car=evt.getKeyChar();
        if((car<'0' || car>'9')&& (car<'.' || car>'.')) evt.consume();
        if(pantalla.getText().length()==3){
          double num;
        num=Double.parseDouble(pantalla.getText());
        if(num>3.0 &&  num<6.7){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
         }
    }//GEN-LAST:event_pantallaKeyTyped

    private void ramKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ramKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            garantia.requestFocus();
        }   
    }//GEN-LAST:event_ramKeyPressed

    private void ramKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ramKeyTyped
        char car=evt.getKeyChar();
        if((car<'0' || car>'9')&& (car<'.' || car>'.')) evt.consume();
        if(ram.getText().length()==3){
                double num;
        num=Double.parseDouble(ram.getText());
        if(num>0.5 && num<6.0){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        }
    }//GEN-LAST:event_ramKeyTyped

    private void garantiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_garantiaKeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            precio.requestFocus();
        }   
    }//GEN-LAST:event_garantiaKeyPressed

    private void garantiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_garantiaKeyTyped
         char car=evt.getKeyChar();
        if((car<'0' || car>'9')&& (car<'.' || car>'.')) evt.consume();
        if(garantia.getText().length()==3){
          double num;
        num=Double.parseDouble(garantia.getText());
        if(num>1 && num<24){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
         }
    }//GEN-LAST:event_garantiaKeyTyped

    private void precioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioKeyPressed

    private void precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyTyped
         char car=evt.getKeyChar();
        if((car<'0' || car>'9')&& (car<'.' || car>'.')) evt.consume();
        if(precio.getText().length()==5){
       double num;
        num=Double.parseDouble(precio.getText());
        if(num>=0.01 && num<999.99){
           evt.consume();
        Toolkit.getDefaultToolkit().beep();
        }
        }
    }//GEN-LAST:event_precioKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          menuprincipal ventana = new menuprincipal(); 
          ventana.setVisible(true);
            ventana.setLocationRelativeTo(null);
             dispose();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIA3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIA3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbmarca;
    private javax.swing.JTextField cpu;
    private javax.swing.JButton ejecutar;
    private javax.swing.JCheckBox flash;
    private javax.swing.JTextField garantia;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> mostrar;
    private javax.swing.JTextField pantalla;
    private javax.swing.JTextField precio;
    private javax.swing.JCheckBox principal;
    private javax.swing.JTextField principal1;
    private javax.swing.JTextField ram;
    private javax.swing.JCheckBox secundaria;
    private javax.swing.JTextField secundaria1;
    // End of variables declaration//GEN-END:variables
}
